import IOptions from "../Interfaces/IOptions"

const options: IOptions = {
  mainDevices: [
    ['MESH системы'],
    'ZTE Mesh-Wi-Fi ZXHN H196Q',
    ['Оптические терминалы'],
    'Transservice TS-4022',
    'Eltex NTU-RG-1421G-WZ',
    'Eltex NTU-RG-1421G-Wac',
    'Sercomm RV6699',
    'Sercomm RT-GM-1',
    'Huawei RT-GM-2',
    'ISKRATEL RT-GM-3',
    'ISKRATEL RT-GM2-9',
    'ZTE RT-GM-4',
    'ZTE RT-GM-5',
    'ZTE RT-GM-6',
    'Huawei Game RT-X',
    'ZTE F612',
    'ZTE F670',
    'Eltex NTU-2V',
    'Huawei HG 8120H',
    'Huawei HG 8247',
    'Huawei HG 8245H',
    'Huawei HG 8245',
    'Huawei HG 8240',
    'Huawei HG 850a',
    'Huawei HG 850',
    'D-Link DPN R5402',
    'D-Link DPN 5402',
    'Sagemcom F@st 5650',
    'ATRON RFT-630',
    ['Роутеры'],
    'ZTE H298А',
    'ZXHN H118N',
    'Sercomm s1010',
    'Innbox E70',
    'Innbox E80',
    'Sagemcom F@st 1744',
    'D-Link DIR-100',
    'D-Link DIR-100F',
    'D-Link DIR-300',
    'D-Link DIR-620',
    'D-Link DIR-850L',
    'D-Link DIR-825AC',
    ['DSL Модемы'],
    'QTECH QDSL-1040W v2 ADSL+',
    'ZTE ZXHN H108N',
    'D-Link DSL-2640',
    'D-Link DSL-2500',
    'D-Link DVA-3672',
    'Sagemcom Fast 1704 RT',
    'UPVEL UR-344AN4G',
    'Huawei HG 532E',
    'Intercross 5633',
    'Sagemcom F@st 2804',
    'TP-Link&nbsp;TD854W',
    'Acorp Sprinter W422G AnnexA ',
    ['Кабельные модемы'],
    'Arris CM820S-CE',
    'Arris CM900',
    'Arris CM550B',
    'Thomson TCM471',
    'Huawei CG101002',
    'WebSTAR EPC2100R2',
    'Motorolla SB5101E',
    ['Устройство абонента'],
    'Устройство абонента'
  ],
  optionalDevices: [
    ['MESH системы'],
    'ZTE Mesh-Wi-Fi ZXHN H196Q',
    ['Wi - Fi Роутер'],
    'Innbox E70',
    'Innbox E80',
    'Sercomm s1010',
    'ZTE ZXHN H118N',
    'ZTE H298А',
    'Sagemcom F@st 1744',
    'Sagemcom F@st 2804',
    'D-Link DSL-2640',
    'D-Link DIR-300',
    'D-Link DIR-620',
    'D-Link DIR-850L',
    'D-Link DIR-825AC',
    'Netgear WNR1000',
    'Netgear WNR3500L',
    ['Роутер + VOIP'],
    'D-Link DVG5402SP',
    'D-Link DVG5404',
    'D-Link DVG5408',
    'D-Link DVG7111S',
    'Eltex 1404',
    'Eltex RG-1402G',
    'Eltex TAU1',
    ['Коммутаторы'],
    'D-Link DIR-100',
    'D-Link DIR-100F',
    'Tp-link 1005',
    ['Устройство абонента'],
    'Устройство абонента'
  ],
  stb: [
    ['IPTV'],
    'Q-Box',
    'Transervis IPDC603',
    'SuperWave STB IP6003 (Wink+)',
    'ZXV10 B700V7L ZTE',
    'ZXV10 B866 V2 (Wink+)',
    'mag250',
    'vip19x3',
    'VIP1003G Motorola',
    'Hybroad Z123',
    'sml282',
    'sml482',
    'SML-5050',
    'sml723',
    'HD mini',
    'ps7105',
    'RT STB HD',
    'yuxing',
    'zyxel',
    'Switron IPTV-1500 STB',
    'IP TV Sercomm STB 122A (Wink+)',
    'WINK',
    ['DVB - C'],
    'Mezzo SP1505',
    'OPTICUM HD XC-02',
    'Humax CXHD-5151C/RU',
    'KAON KCF-220SCO',
    'KAON KCF-ES270CO',
    'KAON KSC S 660 HD',
    'KAON KSC SA700PCO HD',
    'SMIT Conax',
  ],
  optionalServices: [
    'Диагностика ок / жалоб нет',
    'Диагностика не ок / клиент отказался от диагностики',
    'Диагностика ок / клиент отказался от диагностики',
    'Моноуслуга',
  ],
  faults: [
    ['СРЕ'],
    'Замена CAM-модуля/смарткарты',
    'Не работает через PLC/видеосендеры',
    'Замена ONT, в связи с ТП > 100 Мбит/с',
    'Нет индикации STB/ресивере',
    'Не загружается STB(красно-зеленый индикатор HD mini)',
    'Нет индикации на ONT, ADSL /DOCSIS модеме',
    'Нет индикации на роутере/свитче',
    ['Internet'],
    'Прерывается сессия',
    'Проверка линии на возможность увеличения ТП ADSL',
    'Низкая скорость напрямую',
    'Нет сессии. Требуется настройка CPE',
    'Есть сессия. Требуется настройка CPE',
    'Есть сессия - не открываются страницы, диагностику не выполнить клиент слабый пользователь, отказывается от выполнения действий',
    'Нет сессии -  настройку не выполнить клиент слабый пользователь, отказывается от выполнения действий',
    ['IPTV'],
    'Замена ПДУ',
    'TB не реагирует на ПДУ',
    'Не загружается STB (ошибки нет IP-адреса, загрузка модулей ядра, сетевой интерфейс не подключен, не принимает логин/пароль)',
    'Нет сигнала на ТВ',
    'Низкое качество изображения/рассыпания картинкиi',
    'Отсутствие/низкое качество звукаi',
    'Зависание STBi',
    'Самопроизвольное отключение STBi',
    ['SIP'],
    'Нет входящий или исходящей связи',
    'Нет регистрации на ssw',
    'Нет зуммера/при наличии синхронизации',
    'Плохое качество звука (прерывания, шумы, посторонние звуки)',
    ['Wi - Fi'],
    'Не открываются страницы по Wi-Fi, сессия есть',
    'Низкая скорость по Wi-Fi',
    'Прерывания Wi-Fi',
    ['DOCSIS'],
    'Сигнал на отводе ТУ, требуется проверка в квартире',
    'СЭЛС+СТОК',
    'VB-C Замена ПДУ',
    ['Клиент'],
    'Выезд по требованию клиента (удерживаемый, скандальный, претензионный)',
    'Выезд с тестовым ПК для демонстрации услуги',
    'Выезд с тестовым ТА+линейным шнуром  для демонстрации услуги',
    ['Общие'],
    'Продажа оборудования на выезде',
    'Замена расходников',
    'Нет синхронизации (индикация есть)',
    'Ошибки при инсталляции',
    'Плохие параметры линии, низкий уровень Rx, ошибки Оптика/LAN',
    'Инсталляция без демонстрации, требуется собрать СП',
    'Некорректная коммутация на ККМ',
    'Неисправна абонентская трубка/линия',
    'Неисправна панель',
  ],
}

export default options
